# -*- coding: utf-8 -*-
"""YOLO_Phase3_Phase4_Silver_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1on1Pw8VwUpQv6By4VmdEod4BKnlmhMYV

# 🔬 Silver Lining Detection on Textile Spindles — Phase 3 & 4
## YOLOv8n-Based Computer Vision System

**Project:** Automated Silver Lining Detection on Industrial Spindles  
**Phase:** 3 (Model Development & Testing) → 4 (Optimization & Validation)  
**TRL Level:** TRL 3 → TRL 5  
**Model:** YOLOv8n | **Dataset:** 212 annotated spindle images | **Class:** `silver_lining`

---

## ⚙️ Step 1 — Mount Google Drive & Setup
"""

# ─── Mount Google Drive ───────────────────────────────
from google.colab import drive
try:
    drive.flush_and_unmount()
    print("🔄 Unmounted previous session")
except:
    print("ℹ️  No previous mount")

drive.mount('/content/drive', force_remount=True)
print("✅ Drive mounted!")

import os

project_dir = "/content/drive/MyDrive/Colab spindle_project "
contents = os.listdir(project_dir)
print("📁 Project directory contents:")
for item in contents:
    print(f"   • {item}")

"""## 📦 Step 2 — Install Dependencies (Phase 3 Requirements)"""

# ─── Install all required packages ───────────────────
!pip install ultralytics -q
!pip install onnxruntime -q
!pip install seaborn scikit-learn -q

from ultralytics import YOLO
import torch, os, shutil, yaml
import numpy as np
import cv2
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.gridspec import GridSpec
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

print(f"✅ PyTorch: {torch.__version__}")
print(f"✅ GPU Available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"   GPU: {torch.cuda.get_device_name(0)}")
    print(f"   VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
print("✅ All packages ready!")

"""## 🗂️ Step 3 — Dataset Preparation & Validation (Phase 3: Unit Testing)"""

# ─── Phase 3: Data Pipeline Verification ─────────────
BASE_DIR = project_dir
IMG_DIR  = os.path.join(BASE_DIR, "annotated_silver")
YAML_PATH = "/content/dataset.yaml"

print("=" * 55)
print("  PHASE 3 — DATA PIPELINE VALIDATION")
print("=" * 55)

# Count files
jpg_files = [f for f in os.listdir(IMG_DIR) if f.endswith('.jpg')]
txt_files = [f for f in os.listdir(IMG_DIR) if f.endswith('.txt')]
print(f"\n📊 Dataset Summary:")
print(f"   JPG images : {len(jpg_files)}")
print(f"   TXT labels : {len(txt_files)}")

# ─── Fix filename mismatch ───────────────────────────
print("\n🔧 Checking filename alignment...")
fixed = 0
for jpg in jpg_files:
    base     = os.path.splitext(jpg)[0]
    expected = base + '.txt'
    original = base.replace("annotated_", "") + '.txt'
    orig_path = os.path.join(IMG_DIR, original)
    expt_path = os.path.join(IMG_DIR, expected)
    if os.path.exists(orig_path) and not os.path.exists(expt_path):
        shutil.move(orig_path, expt_path)
        fixed += 1

print(f"   Fixed mismatches: {fixed}")

# Re-verify
txt_files = [f for f in os.listdir(IMG_DIR) if f.endswith('.txt')]
matched   = sum(1 for j in jpg_files if os.path.splitext(j)[0]+'.txt' in txt_files)
unmatched = len(jpg_files) - matched

print(f"\n✅ Matched pairs  : {matched}/{len(jpg_files)}")
print(f"⚠️  Unmatched imgs : {unmatched}")

# ─── Validate label format ───────────────────────────
print("\n🔍 Validating YOLO label format (sample check)...")
valid_labels, bad_labels = 0, 0
for txt in txt_files[:50]:
    with open(os.path.join(IMG_DIR, txt)) as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) == 5:
                cls, cx, cy, w, h = parts
                if int(cls) == 0 and all(0 <= float(v) <= 1 for v in [cx,cy,w,h]):
                    valid_labels += 1
                else:
                    bad_labels += 1

print(f"   Valid YOLO annotations: {valid_labels}")
print(f"   Invalid annotations   : {bad_labels}")
print("\n✅ Data pipeline validation complete!")

"""## ✂️ Step 4 — Train/Val Split & YOLO Dataset Construction"""

# ─── 80/20 Split with stratified sampling ────────────
train_imgs, val_imgs = train_test_split(
    jpg_files, test_size=0.2, random_state=42
)

print(f"📊 Dataset Split:")
print(f"   Train : {len(train_imgs)} images ({len(train_imgs)/len(jpg_files)*100:.0f}%)")
print(f"   Val   : {len(val_imgs)}  images ({len(val_imgs)/len(jpg_files)*100:.0f}%)")

# ─── Create folder structure ────────────────────────
for split in ['train', 'val']:
    os.makedirs(f"/content/yolo_dataset/images/{split}", exist_ok=True)
    os.makedirs(f"/content/yolo_dataset/labels/{split}", exist_ok=True)

def copy_split(img_list, split_name):
    copied, missing = 0, 0
    for img_file in img_list:
        base  = os.path.splitext(img_file)[0]
        label = base + '.txt'
        shutil.copy(os.path.join(IMG_DIR, img_file),
                    f"/content/yolo_dataset/images/{split_name}/{img_file}")
        src_label = os.path.join(IMG_DIR, label)
        if os.path.exists(src_label):
            shutil.copy(src_label, f"/content/yolo_dataset/labels/{split_name}/{label}")
            copied += 1
        else:
            missing += 1
    print(f"   {split_name}: {copied} copied, {missing} labels missing")

copy_split(train_imgs, "train")
copy_split(val_imgs,   "val")

# ─── Write dataset.yaml ─────────────────────────────
dataset_config = {
    'path'  : '/content/yolo_dataset',
    'train' : 'images/train',
    'val'   : 'images/val',
    'nc'    : 1,
    'names' : {0: 'silver_lining'}
}
with open(YAML_PATH, 'w') as f:
    yaml.dump(dataset_config, f)

print("\n✅ dataset.yaml created:")
!cat /content/dataset.yaml

"""## 🚀 Step 5 — YOLOv8n Training (Phase 3: Prototype Implementation)"""

# ─── Phase 3: Train the model ─────────────────────────
print("=" * 55)
print("  PHASE 3 — PROTOTYPE TRAINING")
print("=" * 55)

model = YOLO('yolov8n.pt')

print(f"\n🧠 Model: YOLOv8n")
print(f"   Parameters : 3.01M")
print(f"   GFLOPs     : 8.2")
print(f"   Input size : 640×640")
print(f"\n🚀 Starting training...")

results = model.train(
    data       = YAML_PATH,
    epochs     = 50,          # Phase 3→4 upgrade: 10→50 epochs
    imgsz      = 640,
    batch      = 16,
    name       = 'silver_lining_v1',
    patience   = 10,           # Early stopping
    save       = True,
    plots      = True,
    optimizer  = 'AdamW',      # Phase 4 optimization
    lr0        = 0.001,        # Tuned learning rate
    lrf        = 0.01,         # LR final factor
    momentum   = 0.937,
    weight_decay = 0.0005,
    warmup_epochs = 3,
    augment    = True,         # Data augmentation
    degrees    = 10.0,         # Rotation aug
    flipud     = 0.5,          # Flip aug
    fliplr     = 0.5,
    mosaic     = 1.0,          # Mosaic augmentation
    hsv_h      = 0.015,
    hsv_s      = 0.7,
    hsv_v      = 0.4,
    conf       = 0.001,
    iou        = 0.6,
    verbose    = True,
)

print("\n✅ Training complete!")
print(f"   Best model saved to: runs/detect/silver_lining_v1/weights/best.pt")

"""## 📊 Step 6 — Validation & Metrics (Phase 4: Experimental Validation)"""

# ─── Phase 4: Validate and compute metrics ───────────
print("=" * 55)
print("  PHASE 4 — EXPERIMENTAL VALIDATION")
print("=" * 55)

best_model = YOLO('runs/detect/silver_lining_v1/weights/best.pt')
metrics    = best_model.val(data=YAML_PATH, conf=0.25, iou=0.6)

print("\n📊 Validation Results:")
print(f"   mAP@0.5       : {metrics.box.map50:.4f}")
print(f"   mAP@0.5:0.95  : {metrics.box.map:.4f}")
print(f"   Precision     : {metrics.box.p[0]:.4f}")
print(f"   Recall        : {metrics.box.r[0]:.4f}")
print(f"   F1-Score      : {2*metrics.box.p[0]*metrics.box.r[0]/(metrics.box.p[0]+metrics.box.r[0]):.4f}")
print(f"   FPS (val)     : {1000/metrics.speed['inference']:.1f}")

print("\n📈 Per-Class Results:")
print(f"   Class 0 (silver_lining): mAP50={metrics.box.map50:.4f}")

"""## 🖼️ Step 7 — Inference on Unseen Images (Non-Annotated)

> **Phase 4 Requirement:** Test on images NOT in training set.  
> Place your raw, unannotated spindle images in `spindle_dataset/` folder in Drive.

"""

import os
import shutil
import glob # Needed for robust image file checking

# ─── Phase 4: Detect on NEW unseen images ────────────────
# ☢  IMPORTANT: Use 'spindle_dataset' (non-annotated raw images),
#               NOT 'annotated_silver' (training set)

TEST_DIR = os.path.join(BASE_DIR, "spindle_dataset")

# Define supported image extensions for a robust check
IMAGE_EXTENSIONS = ('.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.webp', '.heic', '.heif', '.dng', '.avif', '.mpo', '.jp2')

# Function to check if a directory contains valid image files
def directory_contains_valid_images(directory):
    if not os.path.exists(directory):
        return False
    for ext in IMAGE_EXTENSIONS:
        # Check for case-insensitive extensions
        if glob.glob(os.path.join(directory, '*' + ext)) or glob.glob(os.path.join(directory, '*' + ext.upper())):
            return True
    return False

# If no separate test folder or it doesn't contain valid images, create a proper hold-out from annotated set
if not directory_contains_valid_images(TEST_DIR):
    print("ℹ️  No separate spindle_dataset found or it does not contain valid image files.")
    print("   Using 20-image hold-out from annotated set (labels hidden)...")

    # Create a temporary hold-out directory
    test_holdout_dir = "/content/test_holdout"
    os.makedirs(test_holdout_dir, exist_ok=True)

    # Clear previous hold-out content if any, to ensure fresh copy
    for item in os.listdir(test_holdout_dir):
        item_path = os.path.join(test_holdout_dir, item)
        if os.path.isfile(item_path) or os.path.islink(item_path):
            os.unlink(item_path)
        elif os.path.isdir(item_path):
            shutil.rmtree(item_path)

    # Copy only images (not labels) → simulates real-world unannotated scenario
    copied_count = 0
    for img_file in val_imgs[:20]: # Take up to 20 images from the validation set
        src_path = os.path.join(IMG_DIR, img_file)
        if os.path.exists(src_path):
            shutil.copy(src_path,
                        os.path.join(test_holdout_dir, img_file))
            copied_count += 1

    # Update TEST_DIR to point to the hold-out directory
    TEST_DIR = test_holdout_dir
    print(f"   Created hold-out with {copied_count} images in {TEST_DIR}")
else:
    # Count actual image files if TEST_DIR is valid
    image_count = sum(1 for f in os.listdir(TEST_DIR) if f.lower().endswith(IMAGE_EXTENSIONS))
    print(f"✅ Using spindle_dataset: {image_count} valid images found in {TEST_DIR}")

# ─── Run detection ─────────────────────────────
print("\n⌖ Running Silver Lining Detection...")
pred_results = best_model.predict(
    source     = TEST_DIR,
    conf       = 0.25,
    iou        = 0.45,
    save       = True,
    save_txt   = True,
    save_conf  = True,
    show_labels= True,
    show_conf  = True,
    line_width = 2,
    name       = 'silver_detection_test',
    verbose    = True,
)

# ─── Detection summary ───────────────────────
total_det   = sum(len(r.boxes) for r in pred_results)
images_with = sum(1 for r in pred_results if len(r.boxes) > 0)
avg_conf    = np.mean([b.conf.item() for r in pred_results for b in r.boxes]) if total_det>0 else 0

print(f"\n☢ Detection Summary:")
print(f"   Images processed     : {len(pred_results)}")
print(f"   Images with detections: {images_with}")
print(f"   Total detections     : {total_det}")
print(f"   Avg confidence       : {avg_conf:.3f}")
print(f"   Detection rate       : {images_with/len(pred_results)*100:.1f}%")

"""## 📸 Step 8 — Visual Results (Phase 4: Display Detections)"""

# ─── Visualize detection results ──────────────────────
import math

def visualize_detections(pred_results, max_show=12, cols=4):
    detections = [(r, r.orig_img) for r in pred_results if len(r.boxes) > 0]
    no_det     = [(r, r.orig_img) for r in pred_results if len(r.boxes) == 0]

    # Prioritize images with detections
    show_list = (detections + no_det)[:max_show]
    rows      = math.ceil(len(show_list) / cols)

    fig, axes = plt.subplots(rows, cols, figsize=(cols*4, rows*3.2))
    fig.patch.set_facecolor('#0d1117')
    axes = axes.flatten() if rows > 1 or cols > 1 else [axes]

    for idx, (r, img) in enumerate(show_list):
        ax = axes[idx]
        ax.set_facecolor('#0d1117')

        # Show original image (no annotation overlay yet)
        rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        ax.imshow(rgb)

        # Draw each detection box manually
        for box in r.boxes:
            x1, y1, x2, y2 = box.xyxy[0].cpu().numpy().astype(int)
            conf = box.conf.item()
            cls  = int(box.cls.item())

            rect = patches.Rectangle(
                (x1, y1), x2-x1, y2-y1,
                linewidth=2.5, edgecolor='#00ff88', facecolor='none'
            )
            ax.add_patch(rect)
            label = f"silver_lining {conf:.0%}"
            ax.text(x1+2, y1-5, label, color='black', fontsize=7.5, fontweight='bold',
                    bbox=dict(boxstyle='round,pad=0.15',
                              facecolor='#00ff88', edgecolor='none', alpha=0.95))

        fname = os.path.basename(r.path) if hasattr(r, 'path') else f'img_{idx}'
        n_det = len(r.boxes)
        status = f"✅ {n_det} detection{'s' if n_det!=1 else ''}" if n_det > 0 else "⬜ No detection"
        color  = '#00ff88' if n_det > 0 else '#ff7b72'
        ax.set_title(f"{fname[:28]}\n{status}", color=color, fontsize=7.5, fontweight='bold', pad=3)
        ax.axis('off')

    # Hide unused axes
    for ax in axes[len(show_list):]:
        ax.axis('off')

    fig.suptitle('Silver Lining Detection — Non-Annotated Spindle Images\nYOLOv8n | Real-Time Inference',
                 color='white', fontsize=13, fontweight='bold', y=1.01)
    plt.tight_layout()
    plt.savefig('/content/detection_visual_results.png', dpi=150, bbox_inches='tight',
                facecolor='#0d1117')
    plt.show()
    print("\n✅ Visualization saved → /content/detection_visual_results.png")

visualize_detections(pred_results, max_show=12, cols=4)

"""## ⚡ Step 9 — Optimization & ONNX Export (Phase 3→4: TRL 5 Readiness)"""

# ─── Phase 3/4: Optimization & Export ────────────────
print("=" * 55)
print("  PHASE 4 — OPTIMIZATION & EXPORT")
print("=" * 55)

# ─── 1. ONNX Export (Raspberry Pi / Edge deployment) ──
print("\n🔧 Exporting to ONNX...")
best_model.export(format='onnx', dynamic=False, simplify=True, opset=12)
print("✅ ONNX export complete")

# ─── 2. Benchmark speed ───────────────────────────────
import time

def benchmark_model(model_path, source_dir, n_runs=3, is_onnx=False):
    m = YOLO(model_path)
    times = []
    imgs_to_benchmark = [os.path.join(source_dir, f) for f in os.listdir(source_dir)
             if f.lower().endswith(IMAGE_EXTENSIONS)][:5]

    if not imgs_to_benchmark:
        print(f"Warning: No valid images found in {source_dir} for benchmarking.")
        return 0.0, 0.0

    for _ in range(n_runs):
        t0 = time.time()
        if is_onnx:
            # For ONNX models exported with dynamic=False, predict one image at a time
            for img_path in imgs_to_benchmark:
                m.predict(source=img_path, verbose=False, save=False)
        else:
            # For PyTorch models, it's efficient to predict all at once
            m.predict(source=imgs_to_benchmark, verbose=False, save=False)
        times.append((time.time() - t0) / len(imgs_to_benchmark) * 1000)
    return np.mean(times), np.std(times)

print("\n⏱️  Speed Benchmark (ms/image):")
pt_mean, pt_std = benchmark_model(
    'runs/detect/silver_lining_v1/weights/best.pt', TEST_DIR, is_onnx=False)
print(f"   PyTorch (.pt)  : {pt_mean:.1f} ± {pt_std:.1f} ms  ({1000/pt_mean:.0f} FPS)\n")
onnx_path = 'runs/detect/silver_lining_v1/weights/best.onnx'
if os.path.exists(onnx_path):
    onnx_mean, onnx_std = benchmark_model(onnx_path, TEST_DIR, is_onnx=True)
    print(f"   ONNX           : {onnx_mean:.1f} ± {onnx_std:.1f} ms  ({1000/onnx_mean:.0f} FPS)")
    print(f"   Speedup (ONNX) : {pt_mean/onnx_mean:.2f}×")

print(f"\n   Real-time threshold : 33.3 ms (30 FPS)")
final_benchmark_mean = onnx_mean if os.path.exists(onnx_path) else pt_mean
print(f"   Status              : {'✅ REAL-TIME CAPABLE' if final_benchmark_mean < 33.3 else '⚠️  Optimized but sub-RT'}")

"""## 📈 Step 10 — Performance Analysis Plots (Phase 4: Results & Analysis)"""

# ─── Phase 4: Plot training curves ────────────────────
import pandas as pd

csv_path = 'runs/detect/silver_lining_v1/results.csv'
if os.path.exists(csv_path):
    df = pd.read_csv(csv_path)
    df.columns = df.columns.str.strip()

    fig = plt.figure(figsize=(18, 10))
    fig.patch.set_facecolor('#0d1117')
    gs  = GridSpec(2, 3, figure=fig, hspace=0.42, wspace=0.35)

    def sax(ax, title, ylabel=''):
        ax.set_facecolor('#161b22')
        ax.tick_params(colors='#8b949e', labelsize=8)
        ax.set_title(title, color='white', fontsize=10, fontweight='bold', pad=6)
        ax.set_xlabel('Epoch', color='#8b949e', fontsize=8)
        ax.set_ylabel(ylabel, color='#8b949e', fontsize=8)
        for s in ax.spines.values(): s.set_edgecolor('#30363d')
        ax.grid(True, color='#21262d', lw=0.5, ls='--')
        ax.legend(fontsize=8, facecolor='#0d1117', edgecolor='#30363d', labelcolor='white')

    ep = df['epoch'] if 'epoch' in df.columns else range(len(df))

    # Box loss
    ax1 = fig.add_subplot(gs[0,0])
    ax1.plot(ep, df['train/box_loss'], '#58a6ff', lw=2, label='Train')
    ax1.plot(ep, df['val/box_loss'],   '#ff7b72', lw=2, label='Val', ls='--')
    sax(ax1, 'Box Loss', 'Loss')

    # Cls loss
    ax2 = fig.add_subplot(gs[0,1])
    ax2.plot(ep, df['train/cls_loss'], '#58a6ff', lw=2, label='Train')
    ax2.plot(ep, df['val/cls_loss'],   '#ff7b72', lw=2, label='Val', ls='--')
    sax(ax2, 'Classification Loss', 'Loss')

    # DFL loss
    ax3 = fig.add_subplot(gs[0,2])
    ax3.plot(ep, df['train/dfl_loss'], '#58a6ff', lw=2, label='Train')
    ax3.plot(ep, df['val/dfl_loss'],   '#ff7b72', lw=2, label='Val', ls='--')
    sax(ax3, 'DFL Loss', 'Loss')

    # mAP
    ax4 = fig.add_subplot(gs[1,0])
    ax4.plot(ep, df['metrics/mAP50(B)'],     '#3fb950', lw=2, label='mAP@0.5')
    ax4.plot(ep, df['metrics/mAP50-95(B)'],  '#ffa657', lw=2, label='mAP@0.5:0.95')
    sax(ax4, 'mAP Metrics', 'Score')

    # Precision/Recall
    ax5 = fig.add_subplot(gs[1,1])
    ax5.plot(ep, df['metrics/precision(B)'], '#d2a8ff', lw=2, label='Precision')
    ax5.plot(ep, df['metrics/recall(B)'],    '#ff7b72', lw=2, label='Recall')
    sax(ax5, 'Precision & Recall', 'Score')

    # Final metrics bar
    ax6 = fig.add_subplot(gs[1,2])
    ax6.set_facecolor('#161b22')
    last  = df.iloc[-1]
    names = ['Precision', 'Recall', 'mAP@0.5', 'mAP@.5:.95']
    vals  = [last['metrics/precision(B)'], last['metrics/recall(B)'],
             last['metrics/mAP50(B)'],     last['metrics/mAP50-95(B)']]
    bcolors = ['#d2a8ff','#ff7b72','#3fb950','#ffa657']
    bars = ax6.bar(names, vals, color=bcolors, edgecolor='#30363d', width=0.6)
    for b, v in zip(bars, vals):
        ax6.text(b.get_x()+b.get_width()/2, b.get_height()+0.01,
                 f'{v:.3f}', ha='center', va='bottom', color='white', fontsize=9, fontweight='bold')
    for s in ax6.spines.values(): s.set_edgecolor('#30363d')
    ax6.set_facecolor('#161b22')
    ax6.tick_params(colors='#8b949e', axis='x', labelsize=8)
    ax6.tick_params(colors='#8b949e', axis='y')
    ax6.grid(True, color='#21262d', lw=0.5, ls='--', axis='y')
    ax6.set_title('Final Performance Metrics', color='white', fontsize=10, fontweight='bold', pad=6)
    ax6.set_ylim(0, 1.05)

    fig.suptitle('Phase 3 & 4 — Training Metrics | Silver Lining Detection',
                 color='white', fontsize=13, fontweight='bold', y=0.98)
    plt.savefig('/content/training_metrics.png', dpi=150, bbox_inches='tight', facecolor='#0d1117')
    plt.show()
    print("✅ Training metrics chart saved → /content/training_metrics.png")
else:
    print("⚠️  results.csv not found — run training first!")

"""## 🔬 Step 11 — Baseline Comparison (Phase 4: Expected vs Actual)"""

# ─── Phase 4: Compare against baseline & expectations ──
print("=" * 60)
print("  PHASE 4 — EXPECTED vs ACTUAL PERFORMANCE")
print("=" * 60)

# Expected (from literature / initial design targets)
expected = {
    'mAP@0.5'      : 0.80,
    'Precision'    : 0.85,
    'Recall'       : 0.75,
    'mAP@0.5:0.95' : 0.50,
    'FPS'          : 50.0,
}

# Actual (from your trained model — fill from metrics above)
actual = {
    'mAP@0.5'      : metrics.box.map50,
    'Precision'    : metrics.box.p[0],
    'Recall'       : metrics.box.r[0],
    'mAP@0.5:0.95' : metrics.box.map,
    'FPS'          : 1000/metrics.speed['inference'],
}

print(f"\n{'Metric':<20} {'Expected':>12} {'Actual':>12} {'Status':>10}")
print("-" * 56)
for k in expected:
    exp = expected[k]
    act = actual[k]
    delta = act - exp
    status = '✅ MET' if act >= exp else '⚠️  BELOW'
    unit = '' if k == 'FPS' else ''
    print(f"  {k:<18} {exp:>12.3f} {act:>12.3f}  {status}")

# Visualize comparison
fig, ax = plt.subplots(figsize=(10, 5))
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

metrics_list = list(expected.keys())[:4]  # Skip FPS for this plot
x = np.arange(len(metrics_list))
w = 0.35

exp_vals = [expected[m] for m in metrics_list]
act_vals = [actual[m]   for m in metrics_list]

b1 = ax.bar(x - w/2, exp_vals, w, label='Expected (Target)', color='#30363d', edgecolor='#58a6ff', lw=1.5)
b2 = ax.bar(x + w/2, act_vals, w, label='Actual (Trained)',  color='#3fb950', edgecolor='#30363d', lw=1.5)

for b, v in zip(b2, act_vals):
    ax.text(b.get_x()+b.get_width()/2, b.get_height()+0.01,
            f'{v:.3f}', ha='center', va='bottom', color='white', fontsize=9, fontweight='bold')
for b, v in zip(b1, exp_vals):
    ax.text(b.get_x()+b.get_width()/2, b.get_height()+0.01,
            f'{v:.3f}', ha='center', va='bottom', color='#8b949e', fontsize=9)

ax.set_xticks(x)
ax.set_xticklabels(metrics_list, color='#c9d1d9', fontsize=10)
ax.set_ylabel('Score', color='#8b949e')
ax.set_ylim(0, 1.1)
ax.set_title('Expected vs Actual Performance — Silver Lining Detector',
             color='white', fontsize=12, fontweight='bold')
ax.legend(fontsize=9, facecolor='#0d1117', edgecolor='#30363d', labelcolor='white')
ax.tick_params(colors='#8b949e')
for s in ax.spines.values(): s.set_edgecolor('#30363d')
ax.grid(True, color='#21262d', lw=0.5, ls='--', axis='y')

plt.tight_layout()
plt.savefig('/content/expected_vs_actual.png', dpi=150, bbox_inches='tight', facecolor='#0d1117')
plt.show()
print("\n✅ Comparison chart saved → /content/expected_vs_actual.png")

"""## 📉 Step 12 — Confidence Distribution & Error Analysis"""

# ─── Confidence score distribution ───────────────────
confs = [b.conf.item() for r in pred_results for b in r.boxes]
n_imgs = len(pred_results)

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
fig.patch.set_facecolor('#0d1117')

# Histogram
ax1 = axes[0]
ax1.set_facecolor('#161b22')
if confs:
    ax1.hist(confs, bins=20, color='#3fb950', edgecolor='#30363d', alpha=0.85)
    ax1.axvline(np.mean(confs), color='#ffa657', lw=2, ls='--', label=f'Mean={np.mean(confs):.3f}')
    ax1.axvline(0.25, color='#ff7b72', lw=2, ls=':', label='Threshold (0.25)')
    ax1.legend(fontsize=9, facecolor='#0d1117', edgecolor='#30363d', labelcolor='white')
ax1.set_title('Confidence Score Distribution', color='white', fontsize=11, fontweight='bold')
ax1.set_xlabel('Confidence', color='#8b949e')
ax1.set_ylabel('Count', color='#8b949e')
ax1.tick_params(colors='#8b949e')
for s in ax1.spines.values(): s.set_edgecolor('#30363d')
ax1.grid(True, color='#21262d', lw=0.5, ls='--', axis='y')

# Pie: detected vs not detected
ax2 = axes[1]
ax2.set_facecolor('#0d1117')
with_det = sum(1 for r in pred_results if len(r.boxes)>0)
without  = n_imgs - with_det
wedges, texts, autotexts = ax2.pie(
    [with_det, without],
    labels=['Detected', 'Not Detected'],
    autopct='%1.1f%%',
    colors=['#3fb950', '#ff7b72'],
    startangle=90,
    wedgeprops=dict(edgecolor='#0d1117', linewidth=2)
)
for t in texts+autotexts:
    t.set_color('white')
    t.set_fontsize(10)
ax2.set_title(f'Detection Rate\n({n_imgs} images)', color='white', fontsize=11, fontweight='bold')

plt.tight_layout()
plt.savefig('/content/confidence_analysis.png', dpi=150, bbox_inches='tight', facecolor='#0d1117')
plt.show()
print("✅ Confidence analysis saved → /content/confidence_analysis.png")

"""## 💾 Step 13 — Save & Download All Results"""

# ─── Save all outputs to Google Drive ────────────────
RESULTS_DIR = os.path.join(project_dir, "phase3_4_results")
os.makedirs(RESULTS_DIR, exist_ok=True)

files_to_save = [
    ('runs/detect/silver_lining_v1/weights/best.pt',   'best.pt'),
    ('runs/detect/silver_lining_v1/weights/best.onnx', 'best.onnx'),
    ('runs/detect/silver_lining_v1/results.csv',       'training_results.csv'),
    ('/content/training_metrics.png',                  'training_metrics.png'),
    ('/content/detection_visual_results.png',          'detection_visual_results.png'),
    ('/content/expected_vs_actual.png',                'expected_vs_actual.png'),
    ('/content/confidence_analysis.png',               'confidence_analysis.png'),
]

print("💾 Saving results to Google Drive...")
for src, dst in files_to_save:
    dst_path = os.path.join(RESULTS_DIR, dst)
    if os.path.exists(src):
        shutil.copy(src, dst_path)
        size = os.path.getsize(dst_path) / 1024
        print(f"   ✅ {dst:<40} ({size:.0f} KB)")
    else:
        print(f"   ⚠️  {src} not found (run training first)")

# ─── Download to local machine ────────────────────────
print("\n📥 Downloading key files...")
from google.colab import files
for src, dst in files_to_save[:4]:  # weights + metrics
    if os.path.exists(src):
        files.download(src)

print("\n" + "="*55)
print("  🎉 PHASE 3 & 4 COMPLETE!")
print("="*55)
print("\n📋 Summary:")
print(f"   ✅ Model trained & validated (YOLOv8n)")
print(f"   ✅ ONNX export ready (Raspberry Pi / Edge)")
print(f"   ✅ Detection on non-annotated images done")
print(f"   ✅ Performance metrics computed & plotted")
print(f"   ✅ Expected vs Actual analysis done")
print(f"   ✅ All results saved to Google Drive")
print("\n📁 Results saved to:", RESULTS_DIR)
print("\n🔬 TRL Status: TRL 3 → TRL 5 ✅")